Repository microsoft/python-environment-tools, pull requests merged in 2024-06, with the labels that each got.

#24 Updating markdown files
  README.md
  SUPPORT.md
Labels: documentation

#30 Add `rustc` flags for windows
  .cargo/config.toml.disabled
  Cargo.toml
Labels: bug

#33 Use Custom crates feed for azure builds
  .cargo/config.toml.disabled
  Cargo.lock
  Cargo.toml
  crates/pet-cache/Cargo.toml
  crates/pet-conda/Cargo.toml
  crates/pet-core/Cargo.toml
  crates/pet-env-var-path/Cargo.toml
  crates/pet-fs/Cargo.toml
  crates/pet-global-virtualenvs/Cargo.toml
  crates/pet-global/Cargo.toml
  crates/pet-homebrew/Cargo.toml
  crates/pet-jsonrpc/Cargo.toml
  crates/pet-linux-global-python/Cargo.toml
  crates/pet-mac-commandlinetools/Cargo.toml
  crates/pet-mac-python-org/Cargo.toml
  crates/pet-pipenv/Cargo.toml
  crates/pet-poetry/Cargo.toml
  crates/pet-pyenv/Cargo.toml
  crates/pet-python-utils/Cargo.toml
  crates/pet-reporter/Cargo.toml
  crates/pet-venv/Cargo.toml
  crates/pet-virtualenv/Cargo.toml
  crates/pet-virtualenvwrapper/Cargo.toml
  crates/pet-windows-registry/Cargo.toml
  crates/pet-windows-registry/src/lib.rs
  crates/pet-windows-store/Cargo.toml
  crates/pet/Cargo.toml
Labels: feature-request
